spring.application.name=resmail
com.thelastimperial.resmail.queue=mailsender
management.metrics.tags.application="${spring.application.name}"
management.metrics.tags.namespace=develop
management.metrics.tags.instance="${spring.application.name}:${spring.application.instance_id:${random.value}}"
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.prometheus.metrics.export.pushgateway.enabled=true
management.prometheus.metrics.export.pushgateway.address=localhost:9091
management.prometheus.metrics.export.pushgateway.job=resmenubatch
management.prometheus.metrics.export.pushgateway.shutdown-operation=post
management.prometheus.metrics.export.pushgateway.grouping-key.environment=production
