spring:
  application:
    name: resmenu
  datasource:
    url: jdbc:postgresql://localhost:5432/resmenu
    username: resmenu
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
management:
  metrics:
    tags:
      application: ${spring.application.name}
      namespace: develop
      instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

com:
  thelastimperial:
    resmenu:
      security:
        publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqROXV/qR1SExoBjuh1tNxN8N1Y9DTXptkmqx3V7it3mO9TrBXgis/ax2IHwUiAGJ1o2YesAA0dO3R1uAeBzSzSjWrQKHp+SZMTdgNVDVT+oIz7e4wQvxUXid+kybAUnylRtDVudsWkmstCWvdc5OpDMnVzHrNWv83A75YA5icna5guIMOg54Kl0t/B/2Q+OimC67a6gr/Q9dR3pOrNLD0KFEknFZyqcy6LPHunno9cAGEqYRDJsMfqrXt5N5ej9QRoFqN/uG9QzprjmqiautbG28sUMT97yEDhraRIuUG4bamqOhUClXKVQlF+tbnTSTaZvPZVKfX7TPECchOxjysQIDAQAB
        privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCpE5dX+pHVITGgGO6HW03E3w3Vj0NNem2SarHdXuK3eY71OsFeCKz9rHYgfBSIAYnWjZh6wADR07dHW4B4HNLNKNatAoen5JkxN2A1UNVP6gjPt7jBC/FReJ36TJsBSfKVG0NW52xaSay0Ja91zk6kMydXMes1a/zcDvlgDmJydrmC4gw6DngqXS38H/ZD46KYLrtrqCv9D11Hek6s0sPQoUSScVnKpzLos8e6eej1wAYSphEMmwx+qte3k3l6P1BGgWo3+4b1DOmuOaqJq61sbbyxQxP3vIQOGtpEi5Qbhtqao6FQKVcpVCUX61udNJNpm89lUp9ftM8QJyE7GPKxAgMBAAECggEAIud9+3YpjAfFwGjVOVFSjT2FFBz2xnRrUWpAXNR9VmY8aojeKYT9/YKQgmVLMcarh4UEwPaJVMfx0sPjkihVJnBzXRUkHzd0nrHxZSBSYSSN/B/P/t5xy6Fsb6NH7qyu7TRLIxI0jrEd+7S588aK+p/q07fk+EraUS2wMrHVhg6BLwmS+L7JjDHWno+EbWO5mN5/YpKgO6HBt9lJDDi9Z/Luz2/tdoYIBv+Q+npjH52dlhr5EAydiQR4/grfgLB92GuXu9npjMInZ6+K18l6c8chEittFN5K0Fgl6rcFvJK1dulrJ5K8w02XLR2l3dA8X8yU8AK0ZfMFWcgvkvR0FwKBgQDla9RYzoMwSSZ84X9T9gekofD3VEJUrrbwyWkJpfb3sfEJ9/m6bBQQ43Up0N03mgZ+Muir5u/cf/4Jck7Y3xZbJMGHOvEtnnBFrqmFM5/HSqJ5w9sF6mto/ng4UBpF8oWEeHiW3PPkG21QWWO9qvQxH6WnL9HQ7Thlq5S9Ia5qRwKBgQC8qg9k6IQ1QHLDEm6MeGlC1bQpxls4YOXza6Wu6+Y4gj9dtJfxSp87eDEPWMd0KAHm8QOel75mmZ+9fKA1Bqw3VK2iRKMWDMHH2SwPNeR/5zOgYCWuvP84Dk1R0KAIfS3W4iFQWL1PSqvVdZmG0LrcKZGOShPlNP4E4o0fwt4/RwKBgQCdVvBQ34CVUvW0W6pJWMgxHmb2GLFNBm2sgVUqKspPYZffsFNyiMDSPEyUGww8H8QoNJ3hlwYVgSomLGDq10SryW94YPIayThScdEM6zS/Ju5699l0GysC3NJyPG1oX0U2brC1Nl+Fp1G28zc2UtIaBoxDNsZ8tNQi1iOx+jF17QKBgQC4pgC3FFMBA3jOr2V/GgJ7pUjVcgupnDyzB3J7Rupl+CQohC4JvK0nuTTa/lsHtnhWHSEbwQxawpRzElyCSWuYI8pk/KRZWlb2T/ktUeO3wwLmPfPjl5p6tJS8NGHMrSeGHn/YcWGnD0AqhRSju/qGrDCHgL0EId9TzJ+urDx01QKBgQCdrBpCI8hapg5U6FUGMHyYxAPTqSOOQMhLwt18kBNrUQ2T8A7NSnw/D49xxAaaU0gxHfSXmwQ7y9J1miNrffaDyE8t0/39wiT+Nb8wQx/HTxJb39gSjfKg7Cx3qDkmtW41V245zZlkGJX7bkRFA43B/a8lBg9PzxADF7YN/D1H7A==
        keyid: 4ebb6cf4-9bb3-49ba-9acb-5fb6354472ec
      storage:
        path: PATH_STORAGE
        media-types: image/jpeg, image/png
