--
-- PostgreSQL database dump
--

\restrict FiD1bFWxZmYRoim2Ywg4YtSVJZTP15IyJqcFtT2sg9zr3ZZqp7UAuEpHEH1u5v4

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: menus; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.menus (
    id bigint NOT NULL,
    active boolean DEFAULT false NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    phone character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id uuid
);


--
-- Name: menus_id_seq; Type: SEQUENCE; Schema: public; Owner: resmenu
--

ALTER TABLE public.menus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    image_id uuid,
    name character varying(255),
    price double precision,
    updated_at timestamp(6) without time zone NOT NULL,
    menu_id bigint,
    section_id bigint
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: resmenu
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.roles (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: sections; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.sections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    menu_id bigint
);


--
-- Name: sections_id_seq; Type: SEQUENCE; Schema: public; Owner: resmenu
--

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: storage_blobs; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.storage_blobs (
    id uuid NOT NULL,
    byte_size numeric(38,0),
    checksum character varying(255),
    content_type character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    filename character varying(255),
    metadata character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: user_audits; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.user_audits (
    id uuid NOT NULL,
    action smallint,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by uuid,
    user_id uuid,
    CONSTRAINT user_audits_action_check CHECK (((action >= 0) AND (action <= 6)))
);


CREATE TABLE public.user_recoveries (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_used boolean DEFAULT false NOT NULL,
    last_password character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    valid_until_at timestamp(6) without time zone,
    user_id uuid
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL
);


--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.user_settings (
    id uuid NOT NULL,
    account_expired_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    credentials_expired_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id uuid
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: resmenu
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    account_non_expired boolean NOT NULL,
    account_non_locked boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credentials_non_expired boolean NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: menus menus_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT menus_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);


--
-- Name: storage_blobs storage_blobs_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.storage_blobs
    ADD CONSTRAINT storage_blobs_pkey PRIMARY KEY (id);


--
-- Name: user_settings uk4bos7satl9xeqd18frfeqg6tt; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT uk4bos7satl9xeqd18frfeqg6tt UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_role uk872xec3woupu3gw59b04pj3sa; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT uk872xec3woupu3gw59b04pj3sa UNIQUE (user_id, role_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_audits user_audits_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_audits
    ADD CONSTRAINT user_audits_pkey PRIMARY KEY (id);


--
-- Name: user_recoveries user_recoveries_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_recoveries
    ADD CONSTRAINT user_recoveries_pkey PRIMARY KEY (id);


--
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: products fk6ina06wy2nvjja9v3tqqx9xs4; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6ina06wy2nvjja9v3tqqx9xs4 FOREIGN KEY (section_id) REFERENCES public.sections(id);


--
-- Name: user_settings fk8v82nj88rmai0nyck19f873dw; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT fk8v82nj88rmai0nyck19f873dw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: products fkdi00gpihb4lrwudrld7nqv47b; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkdi00gpihb4lrwudrld7nqv47b FOREIGN KEY (menu_id) REFERENCES public.menus(id);


--
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_recoveries fkmtcgsbytmpx96h7mhbdfm74mb; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_recoveries
    ADD CONSTRAINT fkmtcgsbytmpx96h7mhbdfm74mb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: sections fkn3g8730vxdlnjovr32scm24wa; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT fkn3g8730vxdlnjovr32scm24wa FOREIGN KEY (menu_id) REFERENCES public.menus(id);


--
-- Name: menus fkrufxapib25ap0wmq1aaquppw6; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.menus
    ADD CONSTRAINT fkrufxapib25ap0wmq1aaquppw6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_role fkt7e7djp752sqn6w22i6ocqy6q; Type: FK CONSTRAINT; Schema: public; Owner: resmenu
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- PostgreSQL database dump complete
--

\unrestrict FiD1bFWxZmYRoim2Ywg4YtSVJZTP15IyJqcFtT2sg9zr3ZZqp7UAuEpHEH1u5v4

