CREATE TABLE roles (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(255),
    updated_at timestamp(6) without time zone,
    PRIMARY KEY(id)
);

CREATE TABLE users (
    id uuid NOT NULL,
    account_non_expired boolean NOT NULL,
    account_non_locked boolean NOT NULL,
    created_at timestamp(6) without time zone,
    credentials_non_expired boolean NOT NULL,
    email character varying(255),
    enabled boolean NOT NULL,
    password character varying(255),
    updated_at timestamp(6) without time zone,
    username character varying(255),
    PRIMARY KEY(id)
);

CREATE TABLE user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL
);

CREATE TABLE public.menus (
    id bigint NOT NULL PRIMARY KEY,
    active boolean DEFAULT false NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    phone character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id uuid
);

ALTER TABLE public.menus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.sections (
    id bigint NOT NULL PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    menu_id bigint
);

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id bigint NOT NULL PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(255),
    price double precision,
    updated_at timestamp(6) without time zone NOT NULL,
    menu_id bigint,
    section_id bigint
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_settings (
    id uuid NOT NULL PRIMARY KEY,
    account_expired_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    credentials_expired_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id uuid
);

CREATE TABLE public.user_audits (
    id uuid NOT NULL PRIMARY KEY,
    action smallint,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by uuid,
    user_id uuid,
    CONSTRAINT user_audits_action_check CHECK (((action >= 0) AND (action <= 5)))
);
